"""Backward-compatible import facade for the modular HL7 package."""

from healthcare_pipeline.parsers.hl7.core.constants import (
    HL7_DEFAULT_COMPONENT_SEPARATOR,
    HL7_DEFAULT_ENCODING_CHARACTERS,
    HL7_DEFAULT_ESCAPE_CHARACTER,
    HL7_DEFAULT_FIELD_SEPARATOR,
    HL7_DEFAULT_REPETITION_SEPARATOR,
    HL7_DEFAULT_SUBCOMPONENT_SEPARATOR,
    HL7_MINIMUM_MSH_LENGTH,
    HL7_MSH_SEGMENT_NAME,
    HL7_RESERVED_DELIMITER_CHARACTERS,
    HL7_SEGMENT_TERMINATOR,
)

__all__ = [
    "HL7_SEGMENT_TERMINATOR",
    "HL7_MINIMUM_MSH_LENGTH",
    "HL7_MSH_SEGMENT_NAME",
    "HL7_DEFAULT_FIELD_SEPARATOR",
    "HL7_DEFAULT_COMPONENT_SEPARATOR",
    "HL7_DEFAULT_REPETITION_SEPARATOR",
    "HL7_DEFAULT_ESCAPE_CHARACTER",
    "HL7_DEFAULT_SUBCOMPONENT_SEPARATOR",
    "HL7_DEFAULT_ENCODING_CHARACTERS",
    "HL7_RESERVED_DELIMITER_CHARACTERS",
]
