from __future__ import annotations

HL7_SEGMENT_TERMINATOR = "\r"
HL7_MINIMUM_MSH_LENGTH = 8
HL7_MSH_SEGMENT_NAME = "MSH"
HL7_DEFAULT_FIELD_SEPARATOR = "|"
HL7_DEFAULT_COMPONENT_SEPARATOR = "^"
HL7_DEFAULT_REPETITION_SEPARATOR = "~"
HL7_DEFAULT_ESCAPE_CHARACTER = "\\"
HL7_DEFAULT_SUBCOMPONENT_SEPARATOR = "&"
HL7_DEFAULT_ENCODING_CHARACTERS = "^~\\&"

HL7_RESERVED_DELIMITER_CHARACTERS = frozenset({"\r", "\n", "\x00"})
